doctrine:
    dbal:
        
        driver: 'pdo_mysql'
        server_version: 'MariaDB-10.4.10'
        charset: utf8mb4
        host: 127.0.0.1
        port: 3306
        user: root
        password:
        dbname: restaurant
       # url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '10'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
